import = ["/Users/ryancushen/.config/alacritty/themes/themes/challenger_deep.toml"]

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
decorations_theme_variant = "None"
dynamic_padding = true
dynamic_title = true
opacity = 0.8
startup_mode = "Maximized"
title = "Alacritty"

[window.padding]
x = 10
y = 10
