[font.normal]
family = "BerkeleyMono Nerd Font"
style = "Regular"

[window]
decorations = "Transparent"
decorations_theme_variant = "None"
dynamic_padding = true
dynamic_title = true
opacity = 0.9
startup_mode = "Maximized"
title = "Alacritty"

[window.padding]
x = 10
y = 25

[keyboard]
bindings = [
  { key = "Space", mods = "Super|Shift", action = "ToggleViMode" }
]

[general]
import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]
